### ISSUE TITLE
where can we download the PDF of the book

### ISSUE THREAD

**Issue by DeqianBai** [nlp-with-transformers/notebooks#1]
where can we download the PDF of the book， thanks

**Comment by sapaca** [comment]
This book is available through https://learning.oreilly.com and is titled "Natural Language Processing With Transformers." It's incredible and I highly recommend it!

**Comment by lewtun** [comment]
Hi @DeqianBai, as @sapaca mentions you can access the online version on the O'Reilly platform and I believe various electronic formats will be available in the next week or so.

Thank you for your interest in our book 🤗 !
