### ISSUE TITLE
Transformer Anatomy

### ISSUE THREAD

**Issue by sefeoglu** [nlp-with-transformers/notebooks#13]
Hello, 
## Information
There is a missing image in the Images folder for "Transformer Anatomy".

The problem arises in chapter:
* Transformer Anatomy
## Describe the bug
The image given in the file path below does not exist in the Images folder.
```#hide_input
from IPython.display import Image

Image(filename="images/chapter03_bertviz-neuron-light.png")
```

Please could you put this image into the Images folder?
Thanks.

**Comment by lewtun** [comment]
Hey @sefeoglu thank you for opening the issue! These cells were meant to be removed from the notebooks (we can only show figures for Chapter 2), so I've opened a PR to do that.
