### ISSUE TITLE
ResolvePackageNotFound:   - libsndfile

### ISSUE THREAD

**Issue by JingxinLee** [nlp-with-transformers/notebooks#17]
## Describe the bug

When I run the command "conda env create -f environment.yml", it shows:

```
Solving environment: failed

ResolvePackageNotFound:
  - libsndfile
```

## To Reproduce

1. Download ZIP
2. unzip notebooks-main.zip
3. cd notebooks-main
4. conda env create -f environment.yml

**Comment by lewtun** [comment]
Hi @JingxinLee thanks for reporting the issue! I'm not able to reproduce it on Linux, so perhaps you're using a different OS?

Does the following work for you?

```
conda install libsndfile
```

**Comment by JingxinLee** [comment]
> Hi @JingxinLee thanks for reporting the issue! I'm not able to reproduce it on Linux, so perhaps you're using a different OS?
> 
> 
> 
> Does the following work for you?
> 
> 
> 
> ```
> 
> conda install libsndfile
> 
> ```

I'm using Ubuntu 18.04 and 20.04.  I tried conda install libsndfile， but it didn't work.

**Comment by lewtun** [comment]
Hmm, this is quite odd and I can't seem to reproduce it on my end. The last thing I can suggest is trying one of the `conda` commands listed here: https://anaconda.org/conda-forge/libsndfile

Do any of these work for you?

**Comment by JingchaoZhang** [comment]
I am on Ubuntu 20.04 and had the same error. Adding the conda-forge channel in `environment.yml` solves the problem for me.

**Comment by JingxinLee** [comment]
> I am on Ubuntu 20.04 and had the same error. Adding the conda-forge channel in `environment.yml` solves the problem for me.

Thanks a lot. It works. And as for me, I use cudatoolkit 11.1 instead of 11.3.

**Comment by lewtun** [comment]
Thank you both for the suggested solution - with #19 this issue should now be fixed 🥳 !
