### ISSUE TITLE
Can't run on M1 Mac kernel crashing and GPU not detected

### ISSUE THREAD

**Issue by alecl** [nlp-with-transformers/notebooks#41]
## Describe the bug

v11 of cudatoolkit is not available for osx-64. Possibly removed by Nvidia?

https://anaconda.org/anaconda/cudatoolkit
https://developer.nvidia.com/nvidia-cuda-toolkit-11_6_0-developer-tools-mac-hosts

I switch to v9 to get the environment to build, but the GPU is not detected and the kernel crashes running the first command of the first introduction notebook.

```
#hide
from utils import *
setup_chapter()

```

## To Reproduce

1. See error building conda environment ResolvePackageNotFound:  - cudatoolkit=11.3
2. Switch environment.yml to v9 cudatoolkit
3. Attempt to run first notebook command kernel crashes
4. In python note GPU is not found. >>> import torch
>>> torch.cuda.is_available()
False
>>> exit()

## Expected behavior

environment file works as is, GPU is available, kernel doesn't crash on the first command.

**Comment by alecl** [comment]
Reading further references there is Nvidia GPU only support so will have to run in the cloud.

**Comment by lewtun** [comment]
Thanks for reporting the error @alecl ! Yes, unfortunately we can only build the env on NVIDIA GPUs, so will add a note to the README
