### ISSUE TITLE
Chapter 5: Running out of memory

### ISSUE THREAD

**Issue by jgriffi** [nlp-with-transformers/notebooks#56]
## Information

The question or comment is about chapter:

* [ ] Introduction
* [ ] Text Classification
* [ ] Transformer Anatomy
* [ ] Multilingual Named Entity Recognition
* [x] Text Generation
* [ ] Summarization
* [ ] Question Answering
* [ ] Making Transformers Efficient in Production
* [ ] Dealing with Few to No Labels
* [ ] Training Transformers from Scratch
* [ ] Future Directions

## Running out of memory 
After loading gpt2-xl I get this message prompting me to upgrade to Colab Pro:

Your session crashed after using all available RAM. If you are interested in access to high-RAM runtimes, you may want to check out [Colab Pro]

**Comment by 1Maxnet1** [comment]
Hi there,
I'm hitting the same issue. As you marked this as resolved , could you share, how you solved it?
