### ISSUE TITLE
Chapter 6 notebook cannot be run even with datasets  2.0.0 due to datasets load_dataset error may be related to Google Virus scan

### ISSUE THREAD

**Issue by jeromemassot** [nlp-with-transformers/notebooks#62]
## Information

The problem arises in chapter:

* [ ] Introduction
* [ ] Text Classification
* [ ] Transformer Anatomy
* [ ] Multilingual Named Entity Recognition
* [ ] Text Generation
* [X ] Summarization
* [ ] Question Answering
* [ ] Making Transformers Efficient in Production
* [ ] Dealing with Few to No Labels
* [ ] Training Transformers from Scratch
* [ ] Future Directions

## Describe the bug
datasets module cannot load the cnn_dailymail dataset correctly due to bug datasets bug #3787.
The bug should have been fixed in datasets v 2.0.0 release but the notebook env is using v 1.16.1.
After upgrading the datasets lib to v2.0.0. the bug persists.

## To Reproduce

1. setup_chapter() to check that the datasets version is 1.16.1
2. upgrade the datasets version to 2.0.0
3. dataset = load_dataset("cnn_dailymail", version="3.0.0"°
4. FileNotFoundError: [WinError 3]

## Expected behavior

The dataset should be loaded flawlessly as the bug #3787 has been said closed and the problem solved.

**Comment by gcmsrc** [comment]
Please use this dataset >>> `ccdv/cnn_dailymail` unless you are running the notebook in Colab. 
Please also see this [thread](https://github.com/huggingface/datasets/issues/996)

**Comment by jeromemassot** [comment]
Hi @gcmsrc I confirm that your fix works. I am closing the issue. Thanks.
